# Generated by Django 6.0.3 on 2026-04-17 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_client_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to="accounts.client",
            ),
        ),
    ]
