# Generated by Django 6.0.3 on 2026-05-15 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_site_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='RBACChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_affected', models.CharField(max_length=20)),
                ('module_name', models.CharField(max_length=100)),
                ('from_access', models.BooleanField()),
                ('to_access', models.BooleanField()),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('instructor', 'Instructor'), ('trainee', 'Trainee')], max_length=20)),
                ('module_id', models.CharField(max_length=50)),
                ('has_access', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'role', 'module_id')},
            },
        ),
    ]
