# Generated by Django 6.0.3 on 2026-04-15 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='assigned_trainers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'instructor'}, related_name='assigned_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
