# Generated by Django 6.0.3 on 2026-04-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_submission_dashboard_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="submission",
            new_name="assessments_quiz_id_f479a7_idx",
            old_name="assessments_q_created_371e72_idx",
        ),
        migrations.RenameIndex(
            model_name="submission",
            new_name="assessments_quiz_id_29a2e3_idx",
            old_name="assessments_q_status_7c9e34_idx",
        ),
        migrations.RenameIndex(
            model_name="submission",
            new_name="assessments_user_id_d71570_idx",
            old_name="assessments_u_status_55d935_idx",
        ),
    ]
