# Generated by Django 6.0.3 on 2026-04-05 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "tenant")},
            },
        ),
        migrations.CreateModel(
            name="ContentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="content/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("document", "Document"),
                            ("presentation", "Presentation"),
                            ("image", "Image"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_size", models.BigIntegerField(default=0)),
                ("version", models.CharField(default="v1.0", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("processing", "Processing"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
                ),
                ("duration", models.CharField(blank=True, max_length=20)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                (
                    "permissions",
                    models.CharField(
                        choices=[
                            ("view_only", "View Only"),
                            ("allow_download", "Allow Download"),
                        ],
                        default="view_only",
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("cybersecurity", "Cybersecurity"),
                            ("cloud_computing", "Cloud Computing"),
                            ("devops", "DevOps"),
                            ("data_science", "Data Science"),
                            ("networking", "Networking"),
                            ("software_development", "Software Development"),
                            ("project_management", "Project Management"),
                            ("compliance", "Compliance"),
                            ("ai_ml", "AI/ML"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                            ("ar", "Arabic"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_files",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="content.tag")),
            ],
            options={
                "ordering": ["-upload_date"],
            },
        ),
    ]
