# Generated by Django 6.0.3 on 2026-04-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="compliancealert",
            new_name="dashboard_c_tenant__dcdc69_idx",
            old_name="dashboard_co_tenant__ce78cb_idx",
        ),
        migrations.RenameIndex(
            model_name="compliancealert",
            new_name="dashboard_c_tenant__64e72b_idx",
            old_name="dashboard_co_tenant__ca5de4_idx",
        ),
        migrations.RenameIndex(
            model_name="compliancealert",
            new_name="dashboard_c_tenant__36b812_idx",
            old_name="dashboard_co_tenant__d10ea8_idx",
        ),
        migrations.RenameIndex(
            model_name="trainingsession",
            new_name="dashboard_t_tenant__66cf60_idx",
            old_name="dashboard_tr_tenant__66f1f6_idx",
        ),
        migrations.RenameIndex(
            model_name="trainingsession",
            new_name="dashboard_t_tenant__f33189_idx",
            old_name="dashboard_tr_tenant__97511f_idx",
        ),
        migrations.RenameIndex(
            model_name="trainingsession",
            new_name="dashboard_t_tenant__237578_idx",
            old_name="dashboard_tr_tenant__2f7728_idx",
        ),
    ]
