# Generated by Django 6.0.3 on 2026-04-05 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("corporate_modern", "Corporate - Modern"),
                            ("minimalist_blue", "Minimalist Blue"),
                            ("academic_formal", "Academic Formal"),
                        ],
                        default="corporate_modern",
                        max_length=30,
                    ),
                ),
                ("enable_soft_expiry", models.BooleanField(default=False)),
                ("enable_recertification_reminder", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="BatchExpiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_group", models.CharField(max_length=200)),
                ("expiry_date", models.DateField()),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_expiries",
                        to="courses.certification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(blank=True, max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "compliance_taxonomy",
                    models.CharField(
                        choices=[
                            ("ISO 27001", "ISO 27001"),
                            ("SOC2", "SOC2"),
                            ("GDPR", "GDPR"),
                            ("HIPAA", "HIPAA"),
                            ("PCI-DSS", "PCI-DSS"),
                            ("NIST", "NIST"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
                (
                    "skills_taxonomy",
                    models.CharField(
                        choices=[
                            ("Threat Analysis", "Threat Analysis"),
                            ("Incident Response", "Incident Response"),
                            ("Penetration Testing", "Penetration Testing"),
                            ("Cloud Architecture", "Cloud Architecture"),
                            ("DevSecOps", "DevSecOps"),
                            ("Risk Management", "Risk Management"),
                            ("Python", "Python"),
                            ("Kubernetes", "Kubernetes"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="accounts.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="certification",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certification",
                to="courses.course",
            ),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="LessonFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="lesson_files/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("document", "Document"),
                            ("presentation", "Presentation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                            ("ar", "Arabic"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("allow_offline_download", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="courses.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("passing_threshold", models.IntegerField(default=85)),
                (
                    "max_attempts",
                    models.IntegerField(
                        choices=[
                            (1, "1 Attempt"),
                            (2, "2 Attempts"),
                            (3, "3 Attempts"),
                            (5, "5 Attempts"),
                            (0, "Unlimited"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                            ("ar", "Arabic"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("question_count", models.IntegerField(default=10)),
                ("randomize", models.BooleanField(default=False)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_assessment",
                        to="courses.course",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="post_assessments",
                        to="questions.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("single_attempt", models.BooleanField(default=True)),
                ("time_limit_minutes", models.IntegerField(default=45)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("hi", "Hindi"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("es", "Spanish"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                            ("ar", "Arabic"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("question_count", models.IntegerField(default=10)),
                ("randomize", models.BooleanField(default=False)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_assessment",
                        to="courses.course",
                    ),
                ),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pre_assessments",
                        to="questions.question",
                    ),
                ),
            ],
        ),
    ]
