# Generated by Django 6.0.3 on 2026-04-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
        ("courses", "0002_alter_course_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                        ],
                        db_index=True,
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_trainings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_assignments",
                        to="courses.course",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_assignments",
                        to="accounts.tenant",
                    ),
                ),
                (
                    "trainee",
                    models.ForeignKey(
                        limit_choices_to={"role": "trainee"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "unique_together": {("trainee", "course")},
            },
        ),
        migrations.AddIndex(
            model_name="trainingassignment",
            index=models.Index(fields=["tenant", "trainee", "status"], name="courses_trai_tenant__7fa7f7_idx"),
        ),
        migrations.AddIndex(
            model_name="trainingassignment",
            index=models.Index(fields=["tenant", "due_date"], name="courses_trai_tenant__614dcc_idx"),
        ),
    ]
