# Generated by Django 6.0.3 on 2026-05-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_trainingassignment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trainingassignment',
            old_name='courses_trai_tenant__7fa7f7_idx',
            new_name='courses_tra_tenant__45a8a5_idx',
        ),

        migrations.RenameIndex(
            model_name='trainingassignment',
            old_name='courses_trai_tenant__614dcc_idx',
            new_name='courses_tra_tenant__12df06_idx',
        ),

        migrations.AlterField(
            model_name='lessonfile',
            name='file_type',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('video', 'Video'),
                    ('document', 'Document'),
                    ('pdf', 'PDF'),
                    ('presentation', 'Presentation'),
                ],
            ),
        ),
    ]