# Generated by Django 6.0.3 on 2026-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_courses_trai_tenant__7fa7f7_idx_courses_tra_tenant__45a8a5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
