# Generated by Django 6.0.3 on 2026-05-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_rbacchangelog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rbacchangelog',
            new_name='rbac_rbacch_timesta_4d7c17_idx',
            old_name='rbac_rbacch_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='rbacchangelog',
            new_name='rbac_rbacch_role_d87a46_idx',
            old_name='rbac_rbacch_role_idx',
        ),
    ]
