from django.urls import path
from .views import (
    DashboardSummaryView,
    DepartmentCompletionView,
    TrainingTrendView,
    UpcomingSessionsView,
    CalendarSessionsView,
    SessionListCreateView,
    SessionDetailView,
    SessionTrainersView,
    ComplianceAlertsView,
    ComplianceAlertNotifyView,
    RecentTrainingHistoryView,
    MyTrainingHistoryView,
    DashboardOverviewView,
    TraineeDashboardView,
    TraineeCoursesView,
    TrainerDashboardView,
    TrainerSessionsView,
)


urlpatterns = [
    path("dashboard/summary/", DashboardSummaryView.as_view(), name="dashboard-summary"),
    path("dashboard/department-completion/", DepartmentCompletionView.as_view(), name="dashboard-department-completion"),
    path("dashboard/training-trend/", TrainingTrendView.as_view(), name="dashboard-training-trend"),
    path("sessions/upcoming/", UpcomingSessionsView.as_view(), name="sessions-upcoming"),
    path("sessions/calendar/", CalendarSessionsView.as_view(), name="sessions-calendar"),
    path("sessions/", SessionListCreateView.as_view(), name="sessions-list-create"),
    path("sessions/<int:session_id>/", SessionDetailView.as_view(), name="sessions-detail"),
    path("sessions/trainers/", SessionTrainersView.as_view(), name="sessions-trainers"),
    path("dashboard/compliance-alerts/", ComplianceAlertsView.as_view(), name="dashboard-compliance-alerts"),
    path("dashboard/compliance-alerts/<int:alert_id>/notify/", ComplianceAlertNotifyView.as_view(), name="dashboard-compliance-alert-notify"),
    path("training-history/recent/", RecentTrainingHistoryView.as_view(), name="training-history-recent"),
    path("training-history/my/", MyTrainingHistoryView.as_view(), name="training-history-my"),
    path("dashboard/overview/", DashboardOverviewView.as_view(), name="dashboard-overview"),
    path("trainee/dashboard/", TraineeDashboardView.as_view(), name="trainee-dashboard"),
    path("trainee/courses/", TraineeCoursesView.as_view(), name="trainee-courses"),
    path("trainer/dashboard/", TrainerDashboardView.as_view(), name="trainer-dashboard"),
    path("trainer/sessions/", TrainerSessionsView.as_view(), name="trainer-sessions"),
]
