# Generated by Django 6.0.3 on 2026-04-20 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_site_client'),
        ('assessments', '0004_rename_assessments_q_created_371e72_idx_assessments_quiz_id_f479a7_idx_and_more'),
        ('courses', '0002_alter_course_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='courses.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='assessments.submission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['employee', 'issued_at'], name='certificate_employe_87253e_idx'), models.Index(fields=['tenant', 'issued_at'], name='certificate_tenant__9ba767_idx')],
            },
        ),
    ]
