# Generated by Django 6.0.4 on 2026-04-23 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_rename_assessments_q_created_371e72_idx_assessments_quiz_id_f479a7_idx_and_more'),
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedcertificate',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='assessments.submission'),
        ),
    ]
