# Generated by Django 6.0.3 on 2026-04-29 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_site_client'),
        ('certificates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedcertificate',
            name='file_path',
        ),
        migrations.AddField(
            model_name='issuedcertificate',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuedcertificate',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='issuedcertificate',
            name='png_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Template name shown in the builder', max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='cert_logos/')),
                ('layout', models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], default='landscape', max_length=20)),
                ('theme', models.CharField(choices=[('corporate_blue', 'Corporate Blue'), ('corporate_dark', 'Corporate Dark'), ('minimalist', 'Minimalist'), ('academic_formal', 'Academic Formal'), ('gold_elegant', 'Gold Elegant')], default='corporate_blue', max_length=30)),
                ('heading_text', models.CharField(default='Certificate of Completion', max_length=300)),
                ('sub_heading', models.CharField(default='This is to certify that', max_length=300)),
                ('body_text', models.TextField(default='has successfully completed the course and demonstrated the required competencies.', help_text='Supports {{employee_name}}, {{course_name}}, {{date}} placeholders')),
                ('footer_text', models.CharField(blank=True, default='', max_length=500)),
                ('trainer_name', models.CharField(blank=True, max_length=150)),
                ('trainer_title', models.CharField(blank=True, default='Authorized Trainer', max_length=150)),
                ('trainer_signature', models.ImageField(blank=True, null=True, upload_to='cert_signatures/')),
                ('validity_days', models.PositiveIntegerField(default=0, help_text='0 = no expiry; >0 = days from issue date')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_templates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_templates', to='accounts.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='issuedcertificate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='certificates.certificatetemplate'),
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['tenant', 'is_active'], name='certificate_tenant__e5c3e5_idx'),
        ),
    ]
